Repository resuminator/resuminator, pull requests merged in 2021-01, with the labels that each got.

#13 #12 Persisting Modules after DnD
  package.json
  src/components/Auth/AuthAPIs.js
  src/components/ResumePaper/Resume.js
  src/components/Settings/settings.actions.js
  src/redux/actionTypes.js
  src/redux/app.actions.js
  src/redux/reducers/propertiesReducer.js
  src/redux/reducers/settings.reducer.js
  src/redux/reducers/skill.reducer.js
Labels: enhancement

#14 Toggle View for Modules on Resume Paper
  package.json
  src/components/Certifications/CertificationInput.js
  src/components/Education/EducationInput.js
  src/components/Experience/ExperienceInput.js
  src/components/Projects/ProjectInput.js
  src/components/ResumePaper/Resume.js
  src/components/Skills/SkillsInput.js
  src/components/common/SwitchButton.js
  src/components/common/ViewToggle.js
Labels: enhancement

#16 Implemented Tags for Experiences & Projects
  package.json
  src/components/Experience/Experience.js
  src/components/Experience/ExperienceInput.js
  src/components/Projects/ProjectInput.js
  src/components/Projects/Projects.js
Labels: Feature

#20 17 user tips
  package.json
  src/components/Education/EducationInput.js
  src/components/Experience/ExperienceInput.js
  src/components/Experience/JobDescription.js
Labels: Patch

#29 Handle Invalid Dates
  src/components/Education/EducationTitle.js
  src/components/Experience/JobTitle.js
  src/components/common/CustomDatePicker.js
  src/utils/Helpers.js
Labels: Patch

#35 Add Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement
